### ISSUE TITLE
Feature Request: Add bgptools_asn_peer_visible to Prometheus endpoint

### ISSUE THREAD

**Issue by sp0rus** [bgptools/issues#102]
URL:
```
Not applicable
```

Browser (User-Agent if you can): 
```
Not applicable
```

Error base64 blob (If a site error):
```
Not Applicable
```

What were you expecting:
```
Not applicable
```

What happened:
```
Not applicable
```

Being able to pull visible peers from the prometheus endpoint would also be nice to have for building grafana dashboards and such. Example of what that might look like based on the example dashboard you provide:

![image](https://github.com/bgptools/issues/assets/682080/056fccb3-eacc-4dac-b912-738534179b8f)

**Comment by benjojo** [comment]
This would likely cause a "[cardinality](https://www.robustperception.io/cardinality-is-key/) explosion" for any customer that would enable it.

The current motivation to only export a peer number is also to discourage someone from alerting on a peer loss, because peers can come and go, or if bgp.tools restarts a BGP session feed, I do not want users alerts going off by me doing that.

For now I am resistant to this idea unless other customers come forward and suggest this
