### ISSUE TITLE
Incorrect calculation of upstream networks

### ISSUE THREAD

**Issue by emjemj** [bgptools/issues#12]
URL:
```
https://bgp.tools/as/42708#connectivity
```

Browser (User-Agent if you can): 
```
N/A
```

Error base64 blob (If a site error):
```
N/A
```

What were you expecting:
```
AS6461 described as a peer of AS42708
```

What happened:
```
AS6461 described as an upstream of AS42708
```

**Comment by benjojo** [comment]
Hi, this is due to transit free networks peering with AS6461, there is a plan to better calculate this. I'll link this issue with the internal tracker

**Comment by nicoduck** [comment]
It might make sense to include whois data when trying to figure out if it's a peer or upstream:
For our AS (21473), 3209 and 1239 are listed as upstreams but they are peers.
AS3209 at least has RPSL entries in their whois entry which does not include out ASn which might be a hint that they are a peer and not an upstream.
Generally it might be worth it to try to calculate that based on multiple route servers. I think 3209 is only announcing to AS6830 and only because they might still be integrating the customers into their own AS.

**Comment by benjojo** [comment]
This should be fixed now

**Comment by sp0rus** [comment]
Sorry for reopening a closed issue, but I'm seeing the same problem and AS6461 is the Tier 1 in this instance as well.

AS13781 shows up only as an IPv6 peer for AS14749 even though they are downstream.  For AS14749 IPv6 prefix 2606:fbc0::/32 the graph shows it going through AS7029 to AS6461. AS13781 does advertise this prefix to other upstreams, AS3356 and AS393444, but AS14749 also has direct connectivity to those and prepends the link to AS13781. So AS7029 is the only unique path to a Tier 1 provider unless AS14749 loses connectivity to their other providers.

Perhaps the prepending and mutual upstream ASNs are influencing the calculation so it doesn't show as downstream?

Link: https://bgp.tools/prefix/2606:fbc0::/32#connectivity

Screenshot of graph at time of this comment:
![image](https://github.com/bgptools/issues/assets/682080/f3030767-7185-402f-a83e-96d1ba642e1f)
