### ISSUE TITLE
Feature Request: allow edit users IP for the BGP session

### ISSUE THREAD

**Issue by baragoon** [bgptools/issues#141]
Hi Ben,

Is it possible to allow users to change their IP for the BGP session?
For example, when they change their locations, upstream, or prefix.
For now this is hard case, we can delete the session, but due to the sessions limit, unable to create a new one with the new address.

Thank you in advance.

**Comment by benjojo** [comment]
This won't happen, since I want session's (as in, their ID) to represent a router, so they can be sensibly compared. Allowing users to change the IPs means that is harder to do.

The real issue is that some users are unable to create sessions due to there being a population limit on sessions from hobbynets (or things that share such characteristics), The best thing to do here is to just wait until the count of that falls to under 250 sessions and you can then make sessions.
