### ISSUE TITLE
Changing UUID (type 4 / random) for resources arn't cool (breaking links)

### ISSUE THREAD

**Issue by bwbroersma** [bgptools/issues#157]
URL:
```
https://bgp.tools/prefix/159.46.192.0/18 => https://bgp.tools/rir-owner/3f4796b2-e769-409c-8745-9dd507029457 (404)
```

Browser (User-Agent if you can): 
```
any
```

Error base64 blob (If a site error):
```

```

What were you expecting:
```
Resource UUID's should be more stable links, since https://www.w3.org/Provider/Style/URI.html
```

What happened:
```
Changing UUID (type 4 / random) for resources, breaking over (short) times and even on the live site following links.
```

**Comment by benjojo** [comment]
I am not in control of these resources IDs, the RIRs are.

bgp.tools tries to resolve the RIPE NCC Member "tag" for each account, but the example you give appears to relate to Legacy/PI space. So I cannot do that because there is no tag linked to it.

In this case, the tag changed in the last 24 hours (I assume) to `46f762d1-b3ba-45f1-9f06-6ec5c42d9480`, the site caches a lot of this stuff and so it may take a while to change on the site.

I have no sane way to normalise a ID that another data source provides me, though I accept that maybe the cache should be cleared if the underlying data source is updated

**Comment by bwbroersma** [comment]
Thanks for the quick response, I wasn't ware this is actually a RIPE NCC API issue.
Would a workaround be using a deterministic hash of the allocated IP space for the URL?
(in this case `hash("[ipv4] -- 159.46.0.0/16\n")`)
