### ISSUE TITLE
Indicate the use of NAT64 on home page

### ISSUE THREAD

**Issue by ewpratten** [bgptools/issues#88]
On the home page, in the *"You are connecting from"* section, it would be nice to show a note if bgp.tools detects the client being behind NAT64.

I imagine this detection can be done client side with the following steps:
- Make an `AAAA` query to `v4.bgp.tools` 
- If the response exists (or exists, and is in `64:ff9b/96`) then the client is behind DNS64/NAT64
- Show a note or icon of some kind to indicate that the client is not using native IPv4

**Comment by ewpratten** [comment]
Currently, if I view the main page, it just shows that my IPv4 address is a random address out of my NAT64 pool. I personally recognize this address as a pool address, but someone who might not be aware that they are behind a NAT wouldn't know this.

**Comment by benjojo** [comment]
I don't know of a browser API that lets me do a AAAA lookup on a DNS name

**Comment by ewpratten** [comment]
Been thinking about this for a bit. I think I got it. You could have the client make a request to `64:ff9b::185.230.223.124`.

That will fail if they aren't behind NAT64, but hit bgp.tools if they *are*

**Comment by benjojo** [comment]
Need to experiment, but I suspect competent DNS resolvers will filter that
out (if I, an external thing, serve a AAAA 64::blah address)

**Comment by asdfjkluiop** [comment]
That is a bad solution anyway. There's no guarantee the NAT is operating on 64:ff9b::/96...for example nat64.net ...or my own NAT64 which both operate on public prefixes. The only reliable way to test for it is to have the user's browser connect directly to an IPv4 address without the use of DNS. If it fails to connect but can connect to an IPv4 only domain then NAT64 is in use. That's the test that test-ipv6.com used to use before they removed support for it. They removed support for it because let's encrypt won't cert a raw IP and bgp tools will likely have a similar problem.

**Comment by benjojo** [comment]
I generally agree, this is a bit too much of a hack to attempt
